#ifndef QUERY_IMPLICITAGGERATIONOPERATOR_HPP
#define QUERY_IMPLICITAGGERATIONOPERATOR_HPP

#include <dice/query/operators/Operator_predeclare.hpp>


namespace dice::query::operators {

	template<hypertrie::HypertrieTrait_bool_valued htt_t, hypertrie::ByteAllocator allocator_type>
	struct ImplicitAggregationOperator {

		inline static std::generator<CountedEntry<htt_t> const &>
		evaluate(OperandDependencyGraph<htt_t, allocator_type> &odg,
				 std::vector<hypertrie::const_Hypertrie<htt_t, allocator_type>> const &operands,
				 Query<htt_t, allocator_type> const &query,
				 EvaluationContext<htt_t, allocator_type> &evaluation_context,
				 CountedEntry<htt_t> &entry_arg) {
			auto solution_expressions = query.solution_mapping();
			auto solution_entry = CountedEntry<htt_t>::make_with_defaulted_key(solution_expressions.size(), 1);
			if (odg.size() > 0) {// in case the graph is empty, there are not going to be any results generated by the sub_operator
				for (auto const &entry : operators::get_sub_operator<htt_t, allocator_type, false>(odg, operands, query, evaluation_context, entry_arg)) {
					auto cardinality = entry.value();
					while (cardinality > 0) {
						for (auto &expr : solution_expressions) {
							expr.update_value(entry.key());
						}
						cardinality--;
					}
				}
			}
			for (size_t i = 0; i < solution_expressions.size(); i++) {
				solution_entry[i] = solution_expressions[i].evaluate();
			}
			co_yield solution_entry;
		}

	};

}// namespace dice::query::operators

#endif//QUERY_IMPLICITAGGERATIONOPERATOR_HPP
