#ifndef QUERY_LEFTJOINOPERATOR_HPP
#define QUERY_LEFTJOINOPERATOR_HPP

#include <dice/hypertrie/HashJoin.hpp>

#include <dice/query/operators/CardinalityEstimation.hpp>
#include <dice/query/operators/Operator_predeclare.hpp>

#include <boost/container/flat_set.hpp>

namespace dice::query::operators {

	template<hypertrie::HypertrieTrait_bool_valued htt_t, hypertrie::ByteAllocator allocator_type, bool all_tracked_vars_done>
	struct LeftJoinOperator {

	private:
		/**
		 * @brief Finds the empty operands and prunes the provided OperandDependencyGraph.
		 * @param odg: OperandDependencyGraph to be pruned
		 * @param operands: Vector of hypertries
		 * @return a pair consisting of the pruned graph and its corresponding operands
		 */
		inline static std::pair<OperandDependencyGraph<htt_t, allocator_type> *, std::vector<hypertrie::const_Hypertrie<htt_t, allocator_type>>>
		prune_empty(OperandDependencyGraph<htt_t, allocator_type> &odg,
					std::vector<hypertrie::const_Hypertrie<htt_t, allocator_type>> const &operands) {
			std::vector<hypertrie::internal::pos_type> empty_sub_ops{};
			std::vector<hypertrie::const_Hypertrie<htt_t, allocator_type>> pruned_operands{};
			for (size_t pos = 0; pos < operands.size(); pos++) {
				if (operands[pos].empty())
					empty_sub_ops.push_back(pos);
			}
			OperandDependencyGraph<htt_t, allocator_type> *pruned_odg = &odg.prune_graph(empty_sub_ops);
			for (auto pos : pruned_odg->operands_original_positions()) {
				// do not pass scalars corresponding to operands
				// true scalars corresponding to operands are generated by the optional version of HashJoin
				// keep scalars corresponding to filters
				if (operands[pos].depth() > 0 or odg.is_expression(pos))
					pruned_operands.push_back(operands[pos]);
			}
			return std::make_pair(pruned_odg, pruned_operands);
		}

		/**
		 * @brief Checks whether the operator can yield a solution even if the sub_operator does not yield one.
		 * @param odg: OperandDependencyGraph
		 * @return whether all non-optional operands of odg are resolved
		 */
		inline static bool non_opt_evaluated(OperandDependencyGraph<htt_t, allocator_type> &odg) {
			boost::container::flat_set<char> vars{};
			for (auto pos : odg.isc_operands()) {
				auto const &op_labels = odg.operand_var_ids(pos);
				vars.insert(op_labels.begin(), op_labels.end());
				if (vars.size() > 1)
					return false;
			}
			return true;
		}

	public:
		inline static std::generator<CountedEntry<htt_t> const &>
		evaluate(OperandDependencyGraph<htt_t, allocator_type> &odg,
				 std::vector<hypertrie::const_Hypertrie<htt_t, allocator_type>> const &operands,
				 Query<htt_t, allocator_type> const &query,
				 EvaluationContext<htt_t, allocator_type> &evaluation_context,
				 CountedEntry<htt_t> &entry_arg) requires (not all_tracked_vars_done) {
			clear_used_entry_poss<htt_t, allocator_type>(entry_arg, odg, query);
			auto eval_var = CardinalityEstimation<htt_t, allocator_type, true>::getMinCardLabel(odg, operands, query);
			bool is_proj_var = query.is_var_tracked(eval_var);
			uint8_t proj_var_pos;
			if (is_proj_var)
				proj_var_pos = query.tracked_var_position(eval_var);
			const bool evaluated = non_opt_evaluated(odg);
			for (auto &[current_key_part, sub_operands] : hypertrie::HashJoin<htt_t, allocator_type, true>{operands,
																										   odg.var_ids_positions_in_operands(eval_var),
																										   odg.isc_operands()}) {
				evaluation_context.check_time_out();
				if (is_proj_var)
					entry_arg[proj_var_pos] = current_key_part;
				// prune empty operands
				auto [pruned_odg, pruned_sub_operands] = prune_empty(odg, sub_operands);
				auto &sub_odg = pruned_odg->remove_var_id(eval_var);
				if (query.all_tracked_vars_done(sub_odg)) {
					auto &entry = get_sub_operator<htt_t, allocator_type, true>(sub_odg, pruned_sub_operands, query, evaluation_context, entry_arg);
					if (entry.value())
						co_yield entry;
					// yield the current entry if the sub_operator did not yield a solution, and it is allowed
					else if (evaluated) {
						entry_arg.set_value(1);
						co_yield entry_arg;
					}
				} else {
					bool at_least_one_entry = false;
					for (auto const &entry : get_sub_operator<htt_t, allocator_type, false>(sub_odg, pruned_sub_operands, query, evaluation_context, entry_arg)) {
						co_yield entry;
						at_least_one_entry = true;// the sub_operator yielded at least one solution
					}
					// yield the current entry if the sub_operator did not yield a solution, and it is allowed
					if (not at_least_one_entry and evaluated) {
						entry_arg.set_value(1);
						co_yield entry_arg;
					}
				}
				// reset entry
				clear_used_entry_poss<htt_t, allocator_type>(entry_arg, odg, query);
				entry_arg.set_value(1);
			}
		}

		inline static CountedEntry<htt_t> const &
		evaluate(OperandDependencyGraph<htt_t, allocator_type> &odg,
				 std::vector<hypertrie::const_Hypertrie<htt_t, allocator_type>> const &operands,
				 Query<htt_t, allocator_type> const &query,
				 EvaluationContext<htt_t, allocator_type> &evaluation_context,
				 CountedEntry<htt_t> &entry_arg) requires (all_tracked_vars_done) {
			clear_used_entry_poss<htt_t, allocator_type>(entry_arg, odg, query);
			char eval_var = odg.operand_var_ids(odg.isc_operands().front()).front();// need to optimize
			const bool evaluated = non_opt_evaluated(odg);
			[[maybe_unused]] unsigned long value = 0;
			for (auto &[current_key_part, sub_operands] : hypertrie::HashJoin<htt_t, allocator_type, true>{operands,
																										   odg.var_ids_positions_in_operands(eval_var),
																										   odg.isc_operands()}) {
				evaluation_context.check_time_out();
				auto [pruned_odg, pruned_sub_operands] = prune_empty(odg, sub_operands);
				auto &sub_odg = pruned_odg->remove_var_id(eval_var);
				const auto &entry = get_sub_operator<htt_t, allocator_type, true>(sub_odg, sub_operands, query, evaluation_context, entry_arg);
				value += entry.value();
			}
			// yield the current entry if the sub_operator did not yield a solution, and it is allowed
			if (not entry_arg.value() and evaluated)
				value = 1;
			entry_arg.set_value(value);
			return entry_arg;
		}
	};
}// namespace dice::query::operators
#endif//QUERY_LEFTJOINOPERATOR_HPP
