#ifndef QUERY_OPERANDDEPENDENCYGRAPH_HPP
#define QUERY_OPERANDDEPENDENCYGRAPH_HPP

#include <utility>
#include <vector>

#include <boost/container/flat_map.hpp>
#include <boost/container/flat_set.hpp>
#include <boost/graph/adjacency_list.hpp>
#include <boost/graph/connected_components.hpp>
#include <boost/graph/filtered_graph.hpp>
#include <boost/graph/graph_traits.hpp>
#include <boost/graph/strong_components.hpp>
#include <boost/graph/subgraph.hpp>

#include <dice/query/Commons.hpp>
#include <dice/query/Expression.hpp>

namespace dice::query {

	template<hypertrie::HypertrieTrait_bool_valued htt_t, hypertrie::ByteAllocator allocator_type>
	class OperandDependencyGraph {
	private:
		using VariableID = char;
		using VertexSetHash = size_t;
		/* requirements for boost graph */
		struct VertexProperties_t {
			using kind = boost::vertex_property_tag;
		};
		struct EdgeProperties_t {
			using kind = boost::edge_property_tag;
		};
		struct VertexProperties {
			std::vector<VariableID> var_ids;
			FilterExpression<htt_t, allocator_type> filter_expression;
			AssignmentExpression<htt_t, allocator_type> assignment_expression;
			std::shared_ptr<hypertrie::SliceKey<htt_t>> slice_key = nullptr;
			std::optional<size_t> subquery_id = std::nullopt;
			std::optional<size_t> inline_data_id = std::nullopt;
		};
		struct EdgeProperties {
			VariableID var_id = '\0';
			bool is_opt = false;
		};
		using vertex_prop = boost::property<VertexProperties_t,
											VertexProperties>;
		using edge_prop = boost::property<boost::edge_index_t,
										  std::size_t,
										  boost::property<EdgeProperties_t,
														  EdgeProperties>>;
		using DirectedLabelledGraph = boost::subgraph<boost::adjacency_list<boost::vecS,
																			boost::vecS,
																			boost::directedS,
																			vertex_prop,
																			edge_prop>>;
		using LabelledGraph = boost::adjacency_list<boost::vecS,
													boost::vecS,
													boost::undirectedS,
													vertex_prop,
													edge_prop>;

		using Edge = typename DirectedLabelledGraph::edge_descriptor;
		using Vertex = query::operand_desc;

		/* fields */

		// the unique identifier of the dependency graph
		size_t identifier_;
		// hash value of a graph. is calculated using the vertex properties
		size_t hash_ = 0;
		// the dependency graph
		std::unique_ptr<DirectedLabelledGraph> odg_;
		// variable identifiers that have been removed (resolved) up until this point
		// updated in remove_var_id. passed by previous graph
		boost::container::flat_set<char> removed_var_ids_;

		/* graph-level (local) caches */
		struct Cache {
			// the components of a cartesian operation
			std::vector<OperandDependencyGraph> cartesian_components_;
			// the components of a union operation
			std::vector<OperandDependencyGraph> union_components_;
			// the non-optional parts of the query (the vertices that are found in the independent strong component)
			std::vector<Vertex> isc_operands_;
			// the vertices corresponding to filters that are ready to be evaluated
			std::vector<Vertex> filters_for_evaluation_;
			// the vertices corresponding to assignments that are ready to be evaluated
			std::vector<Vertex> assignments_for_evaluation_;
			// whether the var_id participates in a filter
			boost::container::flat_map<char, bool> var_id_in_expressions_;
			// the positions of the operands in the parent graph
			std::vector<Vertex> original_positions_;
			// the graphs generated by pruning a specific set of vertices (uses unique_ptr to ensure ownership)
			ankerl::unordered_dense::map<VertexSetHash, std::unique_ptr<OperandDependencyGraph>> pruned_subgraphs_;
			// the graphs generated by removing a specific variable id (uses unique_ptr to ensure ownership)
			ankerl::unordered_dense::map<VariableID, std::unique_ptr<OperandDependencyGraph>> subgraphs_;
			// the graphs generated by removing a specific set of vertices (uses unique_ptr to ensure ownership)
			ankerl::unordered_dense::map<VertexSetHash, std::unique_ptr<OperandDependencyGraph>> subgraphs_after_removal_;
			// the ids of all variables
			boost::container::flat_set<VariableID> operands_var_ids_set_;
			// the ids of the variables appearing in the independent strong component
			boost::container::flat_set<VariableID> non_optional_var_ids_set_;
			// the ids of the variables appearing only once
			boost::container::flat_set<VariableID> lonely_var_ids_;
			bool lonely_var_ids_evaluated_flag_ = false;// if there are no lonely vars, the function runs multiple times
			// the positions of a particular variable id in each operand
			boost::container::flat_map<VariableID, std::vector<std::vector<Vertex>>> var_ids_positions_in_operands_;
			// the vertices that contain a particular variable id
			boost::container::flat_map<VariableID, std::vector<Vertex>> vertices_with_var_id_;
			// the operands that contain a particular variable id
			boost::container::flat_map<VariableID, std::vector<Vertex>> operands_with_var_id_;
			// the filters (operand_desc) that contain a particular variable id
			boost::container::flat_map<VariableID, std::vector<Vertex>> assignments_with_var_id_;
			// the operands of the ISC that contain a particular variable id
			boost::container::flat_map<VariableID, std::vector<Vertex>> isc_operands_with_var_id_;
			// the filters (operand_desc) of the ISC that contain a particular variable id
			boost::container::flat_map<VariableID, std::vector<Vertex>> isc_assignments_with_var_id_;
			// used in cartesian joins; denotes if the cartesian is between optional components of the query
			bool opt_cartesian_ = false;
		};

		mutable Cache cache_;

	public:
		explicit OperandDependencyGraph(DirectedLabelledGraph const &odg)
			: odg_{std::make_unique<DirectedLabelledGraph>(odg)} {
			static std::atomic<size_t> next_id{0};
			identifier_ = next_id++;
		}

		// the dependency graph is assigned a unique size_t identifier
		// when a dependency graph is copied, its identifier is copied as well
		OperandDependencyGraph() : OperandDependencyGraph{DirectedLabelledGraph{}} {}

		// the cache is not copied
		OperandDependencyGraph(OperandDependencyGraph const &other) {
			assert(this != &other);

			identifier_ = other.identifier_;
			hash_ = other.hash_;
			odg_ = std::make_unique<DirectedLabelledGraph>(*(other.odg_));
			removed_var_ids_ = other.removed_var_ids_;
		}

		OperandDependencyGraph(OperandDependencyGraph &&) = default;

		OperandDependencyGraph &operator=(OperandDependencyGraph const &other) = delete;

		OperandDependencyGraph &operator=(OperandDependencyGraph &&other) noexcept {
			assert(this != &other);

			identifier_ = other.identifier_;
			hash_ = other.hash_;
			odg_ = std::move(other.odg_);
			removed_var_ids_ = std::move(other.removed_var_ids_);
			cache_ = std::move(other.cache_);
			return *this;
		}

		/* graph manipulation */

		/**
		 * @brief Creates a new vertex/operand in the operand dependency graph
		 * @param var_ids: The ids of the variables corresponding to the operand
		 * @param slice_key: The slice key that will be used to create the operand
		 * @return the descriptor(position) of the vertex(operand)
		 */
		Vertex add_operand(std::vector<VariableID> const &var_ids, std::shared_ptr<hypertrie::SliceKey<htt_t>> slice_key) {
			auto desc = boost::add_vertex(*odg_);
			auto v_properties = boost::get(VertexProperties_t(), *odg_);
			v_properties[desc].var_ids = var_ids;
			v_properties[desc].slice_key = std::move(slice_key);
			return desc;
		}

		/**
		 * @brief Creates a new filter vertex/operand in the operand dependency graph.
		 * @param var_ids: The ids of the variables corresponding to the operand
		 * @return the descriptor(position) of the vertex(operand)
		 */
		Vertex add_filter(std::vector<VariableID> const &var_ids, FilterExpression<htt_t, allocator_type> f_expr) {
			auto desc = boost::add_vertex(*odg_);
			auto v_properties = boost::get(VertexProperties_t(), *odg_);
			v_properties[desc].var_ids = var_ids;
			v_properties[desc].filter_expression = std::move(f_expr);
			return desc;
		}

		/**
		 * @brief Creates a new assignment vertex/operand in the operand dependency graph.
		 * @param var_ids: The ids of the variables corresponding to the operand
		 * @return the descriptor(position) of the vertex(operand)
		 */
		Vertex add_assignment(std::vector<VariableID> const &var_ids, AssignmentExpression<htt_t, allocator_type> a_expr) {
			auto desc = boost::add_vertex(*odg_);
			auto v_properties = boost::get(VertexProperties_t(), *odg_);
			v_properties[desc].var_ids = var_ids;
			v_properties[desc].assignment_expression = std::move(a_expr);
			return desc;
		}

		/**
		 * @brief Creates a new subquery vertex/operand in the operand dependency graph.
		 * @param var_ids: The ids of the variables corresponding to the operand
		 * @return the descriptor(position) of the vertex(operand)
		 */
		Vertex add_subquery(std::vector<VariableID> const &var_ids, size_t subquery_id) {
			auto desc = boost::add_vertex(*odg_);
			auto v_properties = boost::get(VertexProperties_t(), *odg_);
			v_properties[desc].var_ids = var_ids;
			v_properties[desc].subquery_id = subquery_id;
			return desc;
		}

		/**
		 * @brief Creates a new subquery vertex/operand in the operand dependency graph.
		 * @param var_ids: The ids of the variables corresponding to the operand
		 * @return the descriptor(position) of the vertex(operand)
		 */
		Vertex add_inline_data(std::vector<VariableID> const &var_ids, size_t inline_data_id) {
			auto desc = boost::add_vertex(*odg_);
			auto v_properties = boost::get(VertexProperties_t(), *odg_);
			v_properties[desc].var_ids = var_ids;
			v_properties[desc].inline_data_id = inline_data_id;
			return desc;
		}

		/**
		 * @brief Creates an edge between two vertices/operands.
		 * The edge is not optional, i.e., it will be used to prune operands.
		 * @param source: The descriptor(position) of the source vertex(operand)
		 * @param target: The descriptor(position) of the target vertex(operand)
		 * @param var_id: The id of the variable that is shared between the two operands. It used to label the edge.
		 */
		void add_dependency(Vertex source, Vertex target, VariableID var_id = '\0') {
			auto desc = boost::add_edge(source, target, *odg_);
			auto e_properties = boost::get(EdgeProperties_t(), *odg_);
			e_properties[desc.first].var_id = var_id;
		}

		/**
		 * @brief Creates all possible edges between two vertices/operands.
		 * The edge is not optional, i.e., it will be used to prune operands.
		 * @param source: The descriptor(position) of the source vertex(operand)
		 * @param target: The descriptor(position) of the target vertex(operand)
		 * @param bidirectional: Denotes whether the dependencies should be bidirectional
		 */
		void add_dependencies(Vertex source, Vertex target, bool bidirectional) {
			auto const &source_var_ids = operand_var_ids(source);
			auto const &target_var_ids = operand_var_ids(target);
			/* find whether they share any var_ids */
			boost::container::flat_set<char> shared_vars{};
			for (auto const &source_var : source_var_ids) {
				if (std::find(target_var_ids.begin(), target_var_ids.end(), source_var) != target_var_ids.end())
					shared_vars.insert(source_var);
			}
			if (not shared_vars.empty()) {
				for (auto const &var : shared_vars) {
					add_dependency(source, target, var);
					if (bidirectional)
						add_dependency(target, source, var);
				}
			}
			/* if they do not share any var_ids, they will be connected with an unlabelled edge */
			else {
				add_dependency(source, target);
				if (bidirectional)
					add_dependency(target, source);
			}
		}

		/**
		 * @brief Creates an edge between two vertices/operands.
		 * The edge is optional, i.e., it will <b>not</b> be used to prune operands.
		 * @param source: The descriptor(position) of the source vertex(operand)
		 * @param target: The descriptor(position) of the target vertex(operand)
		 * @param var_id: The id of the variable that is shared between the two operands. It used to label the edge.
		 */
		void add_connection(Vertex source, Vertex target, VariableID var_id = '\0') {
			auto desc = boost::add_edge(source, target, *odg_);
			auto &new_e_properties = boost::get(EdgeProperties_t(), *odg_)[desc.first];
			new_e_properties.var_id = var_id;
			new_e_properties.is_opt = true;
		}

		/**
		 * @brief Creates a new graph that does not contain the provided vertices.
		 * @param vertices: The vertices that will not be included in the new graph
		 * @return An OperandDependencyGraph
		 */
		OperandDependencyGraph &remove_vertices(std::vector<Vertex> const &vertices) {
			VertexSetHash vertex_set_hash = dice::hash::dice_hash_templates<dice::hash::Policies::wyhash>::dice_hash(vertices);
			// check first if the same set of operands was already provided
			if (cache_.subgraphs_after_removal_.contains(vertex_set_hash))
				return *(cache_.subgraphs_after_removal_[vertex_set_hash]);
			// create a new graph
			auto new_odg = add_entry_to_odg_map(cache_.subgraphs_after_removal_, vertex_set_hash, odg_->create_subgraph()).second.get();
			auto v_iters = boost::vertices(*odg_);
			for (auto v_iter = v_iters.first; v_iter != v_iters.second; v_iter++) {
				if (std::find(vertices.begin(), vertices.end(), *v_iter) == vertices.end())
					boost::add_vertex(odg_->local_to_global(*v_iter), *(new_odg->odg_));
			}
			return *new_odg;
		}

		/**
		 * @brief Creates a new graph which does not include the provided variable id.
		 * The provided variable id is removed from edge and vertex properties.
		 * Vertices corresponding to operands (hypertries) that do not contain any variable ids after the provided variable id
		 * is removed are not included in the new graph, provided remove_op_vertices is set to true (default behaviour).
		 * @param var_id: The variable id to be removed
		 * @return An OperandDependencyGraph
		 */
		[[nodiscard]] OperandDependencyGraph &remove_var_id(VariableID var_id, bool remove_op_vertices = true) {
			/*
			 * As we do not want to remove the variable ids from the current (parent) graph,
			 * we need to copy the current graph to a new graph first. Since the vertices whose
			 * list of variables ids contains only the provided variable id will not be included
			 * in the new graph, they won't be copied to the new graph
			 */
			if (cache_.subgraphs_.contains(var_id))
				return *(cache_.subgraphs_[var_id]);
			auto new_odg = add_entry_to_odg_map(cache_.subgraphs_, var_id, DirectedLabelledGraph{}).second.get();
			auto temp_graph = odg_->create_subgraph();// will contain only the vertices that will be included in the new graph
			auto const &v_properties = boost::get(VertexProperties_t(), *odg_);
			auto v_iters = boost::vertices(*odg_);
			for (auto v_iter = v_iters.first; v_iter != v_iters.second; v_iter++) {
				// we do not want to remove vertices corresponding to expressions as they are not evaluated yet
				// expressions are evaluated after all their labels are resolved (removed)
				if (not remove_op_vertices or
					not v_properties[*v_iter].filter_expression.is_null() or
					not v_properties[*v_iter].assignment_expression.is_null() or
					std::any_of(v_properties[*v_iter].var_ids.begin(), v_properties[*v_iter].var_ids.end(),
								[&](VariableID v_id) { return v_id != var_id; }))
					// need to use global identifier in order to not introduce a new vertex
					boost::add_vertex(odg_->local_to_global(*v_iter), temp_graph);
			}
			// keep original positions (i.e., the positions of the operands in the current graph)
			v_iters = boost::vertices(temp_graph);
			std::vector<Vertex> orig_poss{};
			for (auto v_iter = v_iters.first; v_iter != v_iters.second; v_iter++) {
				orig_poss.push_back(temp_graph.local_to_global(*v_iter));
			}
			// create the new graph
			boost::copy_graph(temp_graph, *(new_odg->odg_));
			// remove the provided variable id from vertex properties
			auto const &v_properties_new = boost::get(VertexProperties_t(), *(new_odg->odg_));
			v_iters = boost::vertices(*(new_odg->odg_));
			for (auto v_iter = v_iters.first; v_iter != v_iters.second; v_iter++) {
				std::erase_if(v_properties_new[*v_iter].var_ids, [&](VariableID v_id) { return v_id == var_id; });
			}
			// remove the provided variable id from edge properties
			auto const &e_properties_new = boost::get(EdgeProperties_t(), *(new_odg->odg_));
			auto e_iters = boost::edges(*(new_odg->odg_));
			for (auto e_iter = e_iters.first; e_iter != e_iters.second; e_iter++) {
				if (auto &v_id = e_properties_new[*e_iter].var_id; v_id == var_id)
					v_id = '\0';
			}
			new_odg->cache_.original_positions_ = std::move(orig_poss);
			new_odg->removed_var_ids_ = removed_var_ids_;
			new_odg->removed_var_ids_.insert(var_id);
			return *new_odg;
		}

		/**
		 * @brief This method removes the provided empty operands along with the operands that transitively depend on them
		 * (i.e., the operands that are reachable via edges that are not optional).
		 * @param empty_operands: The positions of the operands that are empty
		 * @return An OperandDependencyGraph
		 */
		OperandDependencyGraph &prune_graph(std::vector<Vertex> const &empty_operands) {
			VertexSetHash vertex_set_hash = dice::hash::dice_hash_templates<dice::hash::Policies::wyhash>::dice_hash(empty_operands);
			// check first if the same set of operands was already provided
			if (cache_.pruned_subgraphs_.contains(vertex_set_hash))
				return *(cache_.pruned_subgraphs_[vertex_set_hash]);
			auto const &e_properties = boost::get(EdgeProperties_t(), *odg_);
			// create a new graph
			auto sub_graph = add_entry_to_odg_map(cache_.pruned_subgraphs_, vertex_set_hash, odg_->create_subgraph()).second.get();
			boost::container::flat_set<Vertex> pruned{};
			std::deque<Vertex> to_check{empty_operands.begin(), empty_operands.end()};// contains the vertices that need to be visited
			// traverse the graph to find all vertices(operands) that depend on the operands that were provided
			while (not to_check.empty()) {
				auto operand = to_check.front();
				to_check.pop_front();
				if (pruned.find(operand) != pruned.end())
					continue;
				pruned.insert(operand);
				auto out_edge_iters = boost::out_edges(operand, *odg_);
				for (auto out_edge_iter = out_edge_iters.first; out_edge_iter != out_edge_iters.second; out_edge_iter++) {
					if (not e_properties[*out_edge_iter].is_opt)
						to_check.push_back(boost::target(*out_edge_iter, *odg_));
				}
			}
			// the new graph will contain only the vertices that should not be pruned
			auto vertex_iters = boost::vertices(*odg_);
			for (auto vertex_iter = vertex_iters.first; vertex_iter != vertex_iters.second; vertex_iter++) {
				if (pruned.find(*vertex_iter) == pruned.end())
					// need to use global identifier in order to not introduce a new vertex
					boost::add_vertex(odg_->local_to_global(*vertex_iter), *(sub_graph->odg_));
			}
			return *sub_graph;
		}

		/* graph information */

		[[nodiscard]] std::size_t identifier() const noexcept {
			return identifier_;
		}

		[[nodiscard]] std::size_t hash() const noexcept {
			if (not hash_) {
				auto const &v_properties = boost::get(VertexProperties_t(), *odg_);
				for (auto const &v_property : v_properties) {
					hash_ ^= dice::hash::dice_hash_templates<dice::hash::Policies::wyhash>::dice_hash(v_property);
				}
			}
			return hash_;
		}

		[[nodiscard]] boost::container::flat_set<char> const &removed_var_ids() {
			return removed_var_ids_;
		}

		[[nodiscard]] std::size_t size() const {
			return boost::num_vertices(*odg_);
		}

		[[nodiscard]] bool optional_cartesian() const noexcept {
			return cache_.opt_cartesian_;
		}

		[[nodiscard]] bool is_expression(Vertex vertex) const {
			auto const &v_properties = boost::get(VertexProperties_t(), *odg_);
			if (not v_properties[vertex].filter_expression.is_null())
				return true;
			if (not v_properties[vertex].assignment_expression.is_null())
				return true;
			return false;
		}

		[[nodiscard]] bool is_filter(Vertex vertex) const {
			auto const &v_properties = boost::get(VertexProperties_t(), *odg_);
			return not v_properties[vertex].filter_expression.is_null();
		}

		[[nodiscard]] bool is_assignment(Vertex vertex) const {
			auto const &v_properties = boost::get(VertexProperties_t(), *odg_);
			return not v_properties[vertex].assignment_expression.is_null();
		}

		[[nodiscard]] FilterExpression<htt_t, allocator_type> &get_filter(Vertex vertex) {
			auto const &v_properties = boost::get(VertexProperties_t(), *odg_);
			return v_properties[vertex].filter_expression;
		}

		[[nodiscard]] AssignmentExpression<htt_t, allocator_type> &get_assignment(Vertex vertex) {
			auto const &v_properties = boost::get(VertexProperties_t(), *odg_);
			return v_properties[vertex].assignment_expression;
		}

		[[nodiscard]] std::optional<size_t> get_subquery_id(Vertex vertex) {
			auto const &v_properties = boost::get(VertexProperties_t(), *odg_);
			return v_properties[vertex].subquery_id;
		}

		[[nodiscard]] std::optional<size_t> get_inline_data_id(Vertex vertex) {
			auto const &v_properties = boost::get(VertexProperties_t(), *odg_);
			return v_properties[vertex].inline_data_id;
		}

		[[nodiscard]] hypertrie::SliceKey<htt_t> *const get_slice_key(Vertex vertex) {
			auto const &v_properties = boost::get(VertexProperties_t(), *odg_);
			return v_properties[vertex].slice_key.get();
		}

		[[nodiscard]] std::vector<Vertex> const &operands_original_positions() {
			if (not cache_.original_positions_.empty())
				return cache_.original_positions_;
			auto vertices_iterators = boost::vertices(*odg_);
			if (odg_->m_parent) {
				for (auto vertex_iter = vertices_iterators.first; vertex_iter != vertices_iterators.second; vertex_iter++) {
					auto global_desc = odg_->local_to_global(*vertex_iter);
					// store the identifier/descriptor of the parent, not the global
					cache_.original_positions_.push_back(odg_->parent().global_to_local(global_desc));
				}
			} else {
				for (uint8_t i = 0; i < size(); i++) {
					cache_.original_positions_.push_back(i);
				}
			}
			return cache_.original_positions_;
		}


		[[nodiscard]] std::vector<char> const &operand_var_ids(Vertex operand) const {
			auto const &v_properties = boost::get(VertexProperties_t(), *odg_);
			return v_properties[operand].var_ids;
		}

		[[nodiscard]] boost::container::flat_set<char> const &operands_var_ids_set() const {
			if (cache_.operands_var_ids_set_.empty()) {
				auto v_properties = boost::get(VertexProperties_t(), *odg_);
				auto vertex_iters = boost::vertices(*odg_);
				for (auto v_iter = vertex_iters.first; v_iter != vertex_iters.second; v_iter++) {
					auto const &v_iter_properties = v_properties[*v_iter];
					// skip vertices corresponding to filters
					if (not v_iter_properties.filter_expression.is_null())
						continue;
					// skip vertices corresponding to assignments
					if (not v_iter_properties.assignment_expression.is_null())
						continue;
					cache_.operands_var_ids_set_.insert(v_iter_properties.var_ids.begin(), v_iter_properties.var_ids.end());
				}
			}
			return cache_.operands_var_ids_set_;
		}

		[[nodiscard]] boost::container::flat_set<char> const &non_optional_var_ids_set() {
			if (cache_.non_optional_var_ids_set_.empty()) {
				auto v_properties = boost::get(VertexProperties_t(), *odg_);
				auto const &isc_ops = isc_operands();
				for (auto const &isc_op : isc_ops) {
					// skip vertices corresponding to filters
					if (not v_properties[isc_op].filter_expression.is_null())
						continue;
					// skip vertices corresponding to assignments
					if (not v_properties[isc_op].assignment_expression.is_null())
						continue;
					for (auto const &var_id : v_properties[isc_op].var_ids) {
						cache_.non_optional_var_ids_set_.insert(var_id);
					}
				}
			}
			return cache_.non_optional_var_ids_set_;
		}

		[[nodiscard]] std::vector<std::vector<Vertex>> const &var_ids_positions_in_operands(char var_id) const {
			assert(operands_var_ids_set().contains(var_id));
			auto &var_id_positions = cache_.var_ids_positions_in_operands_[var_id];
			if (not var_id_positions.empty())
				return var_id_positions;
			auto v_properties = boost::get(VertexProperties_t(), *odg_);
			auto vertex_iters = boost::vertices(*odg_);
			for (auto v_iter = vertex_iters.first; v_iter != vertex_iters.second; v_iter++) {
				std::vector<Vertex> op_positions{};
				auto const &v_iter_properties = v_properties[*v_iter];
				// visit only the vertices corresponding to operands
				if (v_iter_properties.filter_expression.is_null() and
					v_iter_properties.assignment_expression.is_null()) {
					for (std::size_t pos = 0; pos < v_iter_properties.var_ids.size(); pos++) {
						if (v_iter_properties.var_ids[pos] == var_id)
							op_positions.push_back(pos);
					}
				}
				var_id_positions.push_back(std::move(op_positions));
			}
			return var_id_positions;
		}

		[[nodiscard]] std::vector<Vertex> const &vertices_with_var_id(char var_id) {
			auto found = cache_.vertices_with_var_id_.find(var_id);
			if (found != cache_.vertices_with_var_id_.end()) {
				return found->second;
			}
			auto &vertices = cache_.vertices_with_var_id_[var_id];
			auto v_properties = boost::get(VertexProperties_t(), *odg_);
			auto vertex_iters = boost::vertices(*odg_);
			for (auto v_iter = vertex_iters.first; v_iter != vertex_iters.second; v_iter++) {
				if (std::find(v_properties[*v_iter].var_ids.begin(), v_properties[*v_iter].var_ids.end(), var_id) !=
					v_properties[*v_iter].var_ids.end())
					vertices.push_back(*v_iter);
			}
			return vertices;
		}

		[[nodiscard]] std::vector<Vertex> const &operands_with_var_id(char var_id) {
			assert(operands_var_ids_set().contains(var_id));
			auto found = cache_.operands_with_var_id_.find(var_id);
			if (found != cache_.operands_with_var_id_.end()) {
				return found->second;
			}
			auto &operands = cache_.operands_with_var_id_[var_id];
			auto v_properties = boost::get(VertexProperties_t(), *odg_);
			auto vertex_iters = boost::vertices(*odg_);
			for (auto v_iter = vertex_iters.first; v_iter != vertex_iters.second; v_iter++) {
				// skip vertices corresponding to filters
				if (not v_properties[*v_iter].filter_expression.is_null())
					continue;
				// skip vertices corresponding to assignments
				if (not v_properties[*v_iter].assignment_expression.is_null())
					continue;
				if (std::find(v_properties[*v_iter].var_ids.begin(), v_properties[*v_iter].var_ids.end(), var_id) !=
					v_properties[*v_iter].var_ids.end())
					operands.push_back(*v_iter);
			}
			return operands;
		}

		[[nodiscard]] std::vector<Vertex> const &assignments_with_var_id(char var_id) {
			assert(operands_var_ids_set().contains(var_id));
			auto found = cache_.assignments_with_var_id_.find(var_id);
			if (found != cache_.assignments_with_var_id_.end()) {
				return found->second;
			}
			auto &assignments = cache_.assignments_with_var_id_[var_id];
			auto v_properties = boost::get(VertexProperties_t(), *odg_);
			auto vertex_iters = boost::vertices(*odg_);
			for (auto v_iter = vertex_iters.first; v_iter != vertex_iters.second; v_iter++) {
				// skip vertices not corresponding to assignments
				if (v_properties[*v_iter].assignment_expression.is_null())
					continue;
				if (std::find(v_properties[*v_iter].var_ids.begin(), v_properties[*v_iter].var_ids.end(), var_id) !=
					v_properties[*v_iter].var_ids.end())
					assignments.push_back(*v_iter);
			}
			return assignments;
		}

		[[nodiscard]] std::vector<Vertex> const &isc_operands_with_var_id(char var_id) {
			assert(operands_var_ids_set().contains(var_id));
			auto found = cache_.isc_operands_with_var_id_.find(var_id);
			if (found != cache_.isc_operands_with_var_id_.end()) {
				return found->second;
			}
			auto &operands = cache_.isc_operands_with_var_id_[var_id];
			auto const &isc_ops = isc_operands();
			auto v_properties = boost::get(VertexProperties_t(), *odg_);
			auto vertex_iters = boost::vertices(*odg_);
			for (auto v_iter = vertex_iters.first; v_iter != vertex_iters.second; v_iter++) {
				if (std::find(isc_ops.begin(), isc_ops.end(), *v_iter) == isc_ops.end())
					continue;
				// skip vertices corresponding to filters
				if (not v_properties[*v_iter].filter_expression.is_null())
					continue;
				// skip vertices corresponding to assignments
				if (not v_properties[*v_iter].assignment_expression.is_null())
					continue;
				if (std::find(v_properties[*v_iter].var_ids.begin(), v_properties[*v_iter].var_ids.end(), var_id) !=
					v_properties[*v_iter].var_ids.end())
					operands.push_back(*v_iter);
			}
			return operands;
		}

		[[nodiscard]] std::vector<Vertex> const &isc_assignments_with_var_id(char var_id) {
			assert(operands_var_ids_set().contains(var_id));
			auto found = cache_.isc_assignments_with_var_id_.find(var_id);
			if (found != cache_.isc_assignments_with_var_id_.end()) {
				return found->second;
			}
			auto &assignments = cache_.isc_assignments_with_var_id_[var_id];
			auto const &isc_ops = isc_operands();
			auto v_properties = boost::get(VertexProperties_t(), *odg_);
			auto vertex_iters = boost::vertices(*odg_);
			for (auto v_iter = vertex_iters.first; v_iter != vertex_iters.second; v_iter++) {
				if (std::find(isc_ops.begin(), isc_ops.end(), *v_iter) == isc_ops.end())
					continue;
				// skip vertices not corresponding to assignments
				if (v_properties[*v_iter].assignment_expression.is_null())
					continue;
				if (std::find(v_properties[*v_iter].var_ids.begin(), v_properties[*v_iter].var_ids.end(), var_id) !=
					v_properties[*v_iter].var_ids.end())
					assignments.push_back(*v_iter);
			}
			return assignments;
		}

		[[nodiscard]] boost::container::flat_set<char> const &lonely_var_ids() {
			if (cache_.lonely_var_ids_evaluated_flag_)
				return cache_.lonely_var_ids_;
			boost::container::flat_set<char> visited{};
			auto v_properties = boost::get(VertexProperties_t(), *odg_);
			auto vertex_iters = boost::vertices(*odg_);
			// does not skip assignments nor filters
			for (auto v_iter = vertex_iters.first; v_iter != vertex_iters.second; v_iter++) {
				for (auto const &var_id : v_properties[*v_iter].var_ids) {
					if (cache_.lonely_var_ids_.contains(var_id)) {
						cache_.lonely_var_ids_.erase(var_id);
					} else {
						if (not visited.contains(var_id)) {
							cache_.lonely_var_ids_.insert(var_id);
							visited.insert(var_id);
						}
					}
				}
			}
			cache_.lonely_var_ids_evaluated_flag_ = true;
			return cache_.lonely_var_ids_;
		}
		/* graph algorithms */

		/**
		 * @brief Generates the union components of the query represented by the graph.
		 * The query contains union components if the graph is disconnected.
		 * The connected components of the undirected version of the graph are the union components.
		 * The union components are computed only once.
		 * @return a vector of OperandDependencyGraph
		 */
		std::vector<OperandDependencyGraph> &union_components() const {
			if (not cache_.union_components_.empty()) {
				return cache_.union_components_;
			}
			// create an undirected copy of the graph
			LabelledGraph undirected_graph;
			boost::copy_graph(*odg_, undirected_graph);
			// compute connected components using the undirected version of the graph
			std::vector<Vertex> components(boost::num_vertices(undirected_graph));
			auto num_components = boost::connected_components(undirected_graph, components.data());
			// single connected component -> return the current graph
			if (num_components == 1)
				cache_.union_components_.push_back(*this);
			// multiple connected components -> one subgraph per connected component
			else
				sub_odg(num_components, components, cache_.union_components_);
			return cache_.union_components_;
		}

		/**
		 * @brief Generates the cartesian components of the query represented by the graph.
		 * The process for generating cartesian components is twofold.
		 * First the unlabeled edges of the graph are filtered out.
		 * Then the connected components of the filtered graph are computed.
		 * The connected components are the cartesian components of the original graph.
		 * The cartesian components are computed only once.
		 * @return a vector of OperandDependencyGraph
		 */
		std::vector<OperandDependencyGraph> &cartesian_components() const {
			if (not cache_.cartesian_components_.empty())
				return cache_.cartesian_components_;
			auto const &e_properties = boost::get(EdgeProperties_t(), *odg_);
			auto const &isc_ops = isc_operands();
			// use filtered graph to remove unlabelled edges -- only the unlabeled edges in the ISC are removed
			// if any of the edges is optional, the cartesian is between different optional parts of the query
			using FilteredGraph = boost::filtered_graph<DirectedLabelledGraph,
														std::function<bool(Edge)>, boost::keep_all>;
			auto edge_filter = [&](Edge e_desc) -> bool {
				if (std::find(isc_ops.begin(), isc_ops.end(), e_desc.m_target) == isc_ops.end())
					return true;
				if (e_properties[e_desc].is_opt)
					this->cache_.opt_cartesian_ = true;// TODO: find better solution
				return e_properties[e_desc].var_id;
			};
			FilteredGraph filtered_graph = FilteredGraph(*odg_, edge_filter, boost::keep_all{});
			// the weakly connected components of the filtered graph represent the cartesian components
			// use the undirected graph of the filtered graph to compute the connected components
			LabelledGraph undirected_graph;
			boost::copy_graph(filtered_graph, undirected_graph);
			// make sure that unions will be preserved by adding temporary edges
			for (auto first : isc_ops) {
				for (auto second : isc_ops) {
					if (not boost::edge(first, second, *odg_).second)
						boost::add_edge(first, second, undirected_graph);
				}
			}
			std::vector<Vertex> components(boost::num_vertices(undirected_graph));
			auto num_components = boost::connected_components(undirected_graph, components.data());
			sub_odg(num_components, components, cache_.cartesian_components_);
			return cache_.cartesian_components_;
		}

		/**
		 * @brief Generates the nodes of the graph that belong to the independent strong component (ISC) of the graph.
		 * The ISC of the graph is the root node of the DAG connecting the strong components of the graph.
		 * The nodes of the ISC is generated by finding the strong components of the graph.
		 * The nodes of the ISC are generated only once.
		 * @return a vector of identifiers/positions (uint8_t)
		 */
		std::vector<Vertex> &isc_operands() const {
			if (not cache_.isc_operands_.empty())
				return cache_.isc_operands_;
			// compute the strong components -- https://www.boost.org/doc/libs/1_78_0/libs/graph/example/strong_components.cpp
			std::vector<Vertex> components(boost::num_vertices(*odg_));
			std::vector<Vertex> discover_time(boost::num_vertices(*odg_));
			std::vector<boost::default_color_type> color(num_vertices(*odg_));
			std::vector<Vertex> root(num_vertices(*odg_));
			auto num_components = boost::strong_components(*odg_,
														   make_iterator_property_map(components.begin(), get(boost::vertex_index, *odg_)),
														   root_map(make_iterator_property_map(root.begin(), get(boost::vertex_index, *odg_)))
																   .color_map(
																		   make_iterator_property_map(color.begin(), get(boost::vertex_index, *odg_)))
																   .discover_time_map(make_iterator_property_map(
																		   discover_time.begin(), get(boost::vertex_index, *odg_))));
			// only one strong component -> The ISC is the current graph
			if (num_components == 1) {
				cache_.isc_operands_.resize(boost::num_vertices(*odg_));
				std::iota(cache_.isc_operands_.begin(), cache_.isc_operands_.end(), 0);
			} else {
				// multiple strong components -> The nodes of ISC do not have incoming edges from nodes outside the ISC
				boost::container::flat_set<Vertex> candidates;
				for (auto comp = 0; comp < num_components; comp++)
					candidates.insert(comp);
				auto vertex_iters = boost::vertices(*odg_);
				for (auto iter = vertex_iters.first; iter != vertex_iters.second; iter++) {
					auto adj_v_iters = boost::adjacent_vertices(*iter, *odg_);
					for (auto adj_iter = adj_v_iters.first; adj_iter != adj_v_iters.second; adj_iter++) {
						if (components[*adj_iter] != components[*iter])
							candidates.erase(components[*adj_iter]);
					}
				}
				assert(candidates.size() == 1);
				for (auto iter = vertex_iters.first; iter != vertex_iters.second; iter++) {
					if (candidates.contains(components[*iter]))
						cache_.isc_operands_.push_back(*iter);
				}
			}
			return cache_.isc_operands_;
		}

		/**
		 * @brief Finds the filters of the query that are ready for evaluation.
		 * A filter can be evaluated if it is part of the ISC and all of its variables have already been resolved
		 * (i.e., the vertex does not contain any variable ids).
		 * The vector is created only once.
		 * @return a vector of identifiers/positions (uint8_t)
		 */
		std::vector<Vertex> &filters_for_evaluation() {
			if (cache_.filters_for_evaluation_.empty()) {
				auto const &isc_ops = isc_operands();
				auto const &v_properties = boost::get(VertexProperties_t(), *odg_);
				auto lambda_f = [&](char var_id) {
					for (auto vertex : vertices_with_var_id(var_id)) {
						if (not is_filter(vertex))
							return false;
					}
					return true;
				};
				for (auto isc_op : isc_ops) {
					// skip vertices that do not correspond to filters
					if (v_properties[isc_op].filter_expression.is_null())
						continue;
					auto const &var_ids = v_properties[isc_op].var_ids;
					// check that all var_ids of the filter are resolved
					if (var_ids.empty()) {
						cache_.filters_for_evaluation_.push_back(isc_op);
					}
					// or that the labels appear only in filters
					else if (std::all_of(var_ids.begin(), var_ids.end(), lambda_f)) {
						cache_.filters_for_evaluation_.push_back(isc_op);
					}
				}
			}
			return cache_.filters_for_evaluation_;
		}

		/**
		 * @brief Finds the assignments of the query that are ready for evaluation.
		 * An assignment can be evaluated if it is part of the ISC and all of its variables have already been resolved
		 * (i.e., the vertex does not contain any variable ids).
		 * The vector is created only once.
		 * @return a vector of identifiers/positions (uint8_t)
		 */
		std::vector<Vertex> &assignments_for_evaluation() {
			if (cache_.assignments_for_evaluation_.empty()) {
				auto const &isc_ops = isc_operands();
				auto const &v_properties = boost::get(VertexProperties_t(), *odg_);
				for (auto isc_op : isc_ops) {
					// skip vertices that do not correspond to assignments
					if (v_properties[isc_op].assignment_expression.is_null())
						continue;
					auto const &var_ids = v_properties[isc_op].var_ids;
					// check that all var_ids of the assignment are resolved
					// if only the var_id of the variable to assigned is left, we can resolve the assignment
					if (var_ids.empty() or (var_ids.size() == 1 and var_ids[0] == v_properties[isc_op].assignment_expression.result_var_id())) {
						cache_.assignments_for_evaluation_.push_back(isc_op);
					}
					// or that the labels of the filters do not appear in any operand
					else if (std::all_of(var_ids.begin(), var_ids.end(),
										 [&](char var_id) { return not operands_var_ids_set().contains(var_id); })) {
						cache_.assignments_for_evaluation_.push_back(isc_op);
					}
				}
			}
			return cache_.assignments_for_evaluation_;
		}

		/**
		 * @brief Checks whether the provided var_id participates in an expression in the ISC
		 * @param var_id The var_id to check
		 * @return bool
		 */
		bool var_id_in_expression(char var_id) {
			if (cache_.var_id_in_expressions_.contains(var_id))
				return cache_.var_id_in_expressions_[var_id];
			auto const &isc_ops = isc_operands();
			auto const &v_properties = boost::get(VertexProperties_t(), *odg_);
			for (auto isc_op : isc_ops) {
				// skip vertices that do not correspond to expressions
				if (v_properties[isc_op].filter_expression.is_null() and v_properties[isc_op].assignment_expression.is_null())
					continue;
				// check whether the var_id is part of the expression
				auto const &isc_op_var_ids = v_properties[isc_op].var_ids;
				if (std::find(isc_op_var_ids.begin(), isc_op_var_ids.end(), var_id) != isc_op_var_ids.end()) {
					cache_.var_id_in_expressions_[var_id] = true;
					return true;
				}
			}
			cache_.var_id_in_expressions_[var_id] = false;
			return false;
		}

		/**
		 * @brief Merges the provided operand dependency graphs. Does not introduce new edges.
		 * Should NOT be used once query evaluation has started. Should be used only for building new graphs
		 * @param first An operand dependency graph
		 * @param second An operand dependency graph
		 * @return The merged graph
		 */
		static OperandDependencyGraph
		merge_graphs(OperandDependencyGraph const &first, OperandDependencyGraph const &second) {
			OperandDependencyGraph merged_graph{};
			boost::copy_graph(*(first.odg_), *(merged_graph.odg_));
			boost::copy_graph(*(second.odg_), *(merged_graph.odg_));
			return merged_graph;
		}

		/**
		 * @brief Replaces the variables of vertices corresponding to operands (NOT expressions)
		 * Should NOT be used once query evaluation has started. Should be used only for building new graphs
		 * @param first An operand dependency graph
		 */
		void replace_var_ids_in_operands(boost::container::flat_map<char, char> const &var_ids_replacements) {
			auto v_properties = boost::get(VertexProperties_t(), *odg_);
			auto vertex_iters = boost::vertices(*odg_);
			for (auto v_iter = vertex_iters.first; v_iter != vertex_iters.second; v_iter++) {
				// skip vertices corresponding to filters
				if (not v_properties[*v_iter].filter_expression.is_null())
					continue;
				// skip vertices corresponding to assignments
				if (not v_properties[*v_iter].assignment_expression.is_null())
					continue;
				auto &vertex_var_ids = v_properties[*v_iter].var_ids;
				for (auto &var_id : vertex_var_ids) {
					auto found = var_ids_replacements.find(var_id);
					if (found != var_ids_replacements.end())
						var_id = found->second;
				}
			}
		}

	private:
		/**
		 * @brief Creates an operand dependency graph for each connected component.
		 * @param num_components: The number of components
		 * @param components: The component to which each node belongs to
		 * @param connected_components: Contains the generated dependency graphs
		 */
		void sub_odg(std::size_t num_components,
					 const std::vector<Vertex> &components,
					 std::vector<OperandDependencyGraph> &connected_components) const {
			assert(connected_components.size() == 0);

			connected_components.reserve(num_components);
			for (std::size_t c = 0; c < num_components; c++) {
				auto &component = connected_components.emplace_back(std::move(odg_->create_subgraph()));
				// copy removed_var_ids (not copied through create_subgraph)
				component.removed_var_ids_ = removed_var_ids_;
			}
			for (Vertex vertex = 0; vertex < components.size(); vertex++) {
				// need to use global identifier in order to not introduce a new vertex
				boost::add_vertex(odg_->local_to_global(vertex), *(connected_components[components[vertex]].odg_));
			}
		}

		template<typename id2unique_ptr_map, typename... Args>
		requires(std::is_same_v<typename id2unique_ptr_map::mapped_type, std::unique_ptr<OperandDependencyGraph>>)
		std::pair<typename id2unique_ptr_map::key_type, std::unique_ptr<OperandDependencyGraph>> &
		add_entry_to_odg_map(id2unique_ptr_map &map, typename id2unique_ptr_map::key_type key, Args &&...value_ctor_args) {
			auto new_value = std::pair(key, std::make_unique<OperandDependencyGraph>(std::forward<Args>(value_ctor_args)...));
			return *(map.insert(std::move(new_value)).first);
		}
	};

}// namespace dice::query

#endif//QUERY_OPERANDDEPENDENCYGRAPH_HPP
