#ifndef QUERY_QUERY_HPP
#define QUERY_QUERY_HPP

#include <boost/container/flat_map.hpp>
#include <chrono>
#include <memory>

#include <dice/query/Expression.hpp>
#include <dice/query/OperandDependencyGraph.hpp>

namespace dice::query {

	/**
	 * @brief Contains information about the query to be executed.
	 * @tparam htt_t: Bool-valued Hypertrie trait
	 * @tparam allocator_type: The allocator type
	 */
	template<hypertrie::HypertrieTrait_bool_valued htt_t, hypertrie::ByteAllocator allocator_type>
	class Query {
	private:
		// aliases
		using inline_data_id = size_t;
		using sub_query_id = size_t;
		// for hypertries created during query parsing, this needs to be above all fields that might reference it
		std::shared_ptr<hypertrie::HypertrieContext<htt_t, allocator_type>> tensor_context_;
		// the operand dependency graph of the query
		OperandDependencyGraph<htt_t, allocator_type> odg_;
		// the variables of the query whose value needs to be tracked
		std::vector<char> tracked_vars_;
		// the position of each stored variable
		boost::container::flat_map<char, std::size_t> tracked_vars_pos_;
		// the expressions comprising the solution of the query
		std::vector<ExpressionWrapper<htt_t, allocator_type>> solution_expressions_;
		// the expressions comprising the filters of a solution of the query (e.g., SPARQL's HAVING clause)
		std::vector<ExpressionWrapper<htt_t, allocator_type>> solution_filters_;
		// the expressions comprising the grouping key
		std::vector<ExpressionWrapper<htt_t, allocator_type>> grouping_key_expressions_;
		// the expressions comprising the order by clause
		std::vector<ExpressionWrapper<htt_t, allocator_type>> order_by_expressions_;
		// the type of ordering of each expression (0: asc, 1: desc)
		std::vector<bool> ordering_type_;
		// subqueries; pairs of size_t (identifier) and query
		std::vector<std::pair<sub_query_id, Query<htt_t, allocator_type>>> subqueries_;
		// stores the hypertrie generated by the evaluation of subqueries
		ankerl::unordered_dense::map<sub_query_id, hypertrie::Hypertrie<htt_t, allocator_type>> subquery_operands_;
		size_t subquery_id_ = 0;
		// inline data; pairs of size_t (identifier) and hypertrie
		ankerl::unordered_dense::map<inline_data_id, hypertrie::Hypertrie<htt_t, allocator_type>> inline_data_;
		size_t inline_data_id_ = 0;
		// variables of the query that have already been assigned a value
		boost::container::flat_map<char, typename htt_t::key_part_type> resolved_vars_;
		bool aggregates_ = false;
		bool distinct_ = false;
		// for pagination
		ssize_t offset_ = -1;
		ssize_t limit_ = -1;
		/* for timeouts */
		mutable std::chrono::steady_clock::time_point end_time_ = std::chrono::steady_clock::time_point::max();
		mutable std::chrono::steady_clock::duration time_out_duration_ = std::chrono::steady_clock::duration::max();
		mutable bool has_time_out_ = false;
		static constexpr uint16_t max_time_out_counter_ = 512;
		mutable uint16_t time_out_counter_ = 0;
		/* query level caches */
		// maps a graph to an operator type
		mutable boost::container::flat_map<size_t, Operation> odg_operator_type_;
		mutable boost::container::flat_map<size_t, std::vector<size_t>> odg_tracked_vars_positions_;
		mutable boost::container::flat_map<size_t, bool> odg_contains_tracked_vars_;

	public:
		explicit Query(std::shared_ptr<hypertrie::HypertrieContext<htt_t, allocator_type>> tensor_context) : tensor_context_{std::move(tensor_context)} {
		}

		/* write methods */

		void set_operand_dependency_graph(OperandDependencyGraph<htt_t, allocator_type> graph) noexcept {
			odg_ = std::move(graph);
		}

		size_t add_subquery(Query subquery) {
			auto id = subquery_id_++;
			subqueries_.emplace_back(id, std::move(subquery));
			return id;
		}

		void add_subquery_operand(sub_query_id subquery_id, hypertrie::Hypertrie<htt_t, allocator_type> &&operand) {
			subquery_operands_.emplace(subquery_id, std::move(operand));
		}

		size_t add_inline_data(hypertrie::Hypertrie<htt_t, allocator_type> &&inline_data) {
			assert(inline_data.context() == tensor_context_.get()); // prevent accidentally not using internal context

			auto id = inline_data_id_++;
			inline_data_[id] = std::move(inline_data);
			return id;
		}

		void track_variable(char var) {
			if (tracked_vars_pos_.contains(var))
				return;
			tracked_vars_.push_back(var);
			tracked_vars_pos_[var] = tracked_vars_.size() - 1;
		}

		void assign_value_to_var(char var_id, typename htt_t::key_part_type value) {
			resolved_vars_[var_id] = value;
		}

		void add_binding(ExpressionWrapper<htt_t, allocator_type> expression) {
			solution_expressions_.emplace_back(std::move(expression));
		}

		void add_grouping_expression(ExpressionWrapper<htt_t, allocator_type> expression) {
			grouping_key_expressions_.emplace_back(std::move(expression));
		}

		void set_distinct() {
			distinct_ = true;
		}

		void set_aggregates() {
			aggregates_ = true;
		}

		void set_offset(size_t offset) {
			offset_ = offset;
		}

		void set_limit(size_t limit) {
			limit_ = limit;
		}

		void add_solution_filter(ExpressionWrapper<htt_t, allocator_type> expression) {
			solution_filters_.push_back(std::move(expression));
		}

		void add_ordering(ExpressionWrapper<htt_t, allocator_type> expression, bool desc) {
			order_by_expressions_.push_back(std::move(expression));
			ordering_type_.push_back(desc);
		}

		/* read methods */

		[[nodiscard]] OperandDependencyGraph<htt_t, allocator_type> &operand_dependency_graph() {
			return odg_;
		}

		[[nodiscard]] std::vector<char> const &tracked_vars() const {
			return tracked_vars_;
		}

		[[nodiscard]] std::size_t tracked_var_position(char var) const {
			assert(tracked_vars_pos_.contains(var));
			return tracked_vars_pos_.find(var)->second;
		}

		[[nodiscard]] bool tracks_variable(char var) const {
			return tracked_vars_pos_.contains(var);
		}

		[[nodiscard]] boost::container::flat_map<char, std::size_t> const &tracked_vars_positions() const {
			return tracked_vars_pos_;
		}

		[[nodiscard]] boost::container::flat_map<char, typename htt_t::key_part_type> const &resolved_vars() const {
			return resolved_vars_;
		}

		[[nodiscard]] bool is_var_tracked(char var) const {
			return tracked_vars_pos_.contains(var);
		}

		[[nodiscard]] bool is_distinct() const {
			return distinct_;
		}

		[[nodiscard]] bool contains_aggregates() const {
			return aggregates_;
		}

		[[nodiscard]] ssize_t offset() const {
			return offset_;
		}

		[[nodiscard]] ssize_t limit() const {
			return limit_;
		}

		[[nodiscard]] std::vector<ExpressionWrapper<htt_t, allocator_type>> const &order_by_expressions() const {
			return order_by_expressions_;
		}

		[[nodiscard]] std::vector<bool> const &ordering_type() const {
			return ordering_type_;
		}

		[[nodiscard]] bool explicit_group() const {
			return not grouping_key_expressions_.empty();
		}

		[[nodiscard]] std::vector<ExpressionWrapper<htt_t, allocator_type>> const &solution_mapping() const {
			return solution_expressions_;
		}

		[[nodiscard]] std::vector<ExpressionWrapper<htt_t, allocator_type>> const &solution_filters() const {
			return solution_filters_;
		}

		[[nodiscard]] std::vector<ExpressionWrapper<htt_t, allocator_type>> const &grouping_key() const {
			return grouping_key_expressions_;
		}

		[[nodiscard]] Operation &get_odg_operator_type(OperandDependencyGraph<htt_t, allocator_type> &graph) {
			return odg_operator_type_[graph.identifier()];
		}

		std::vector<std::pair<size_t, Query<htt_t, allocator_type>>> &subqueries() {
			return subqueries_;
		}

		hypertrie::Hypertrie<htt_t, allocator_type> const &inline_data(inline_data_id id) const {
			assert(inline_data_.contains(id));
			return inline_data_.find(id)->second;
		}

		hypertrie::Hypertrie<htt_t, allocator_type> const &subquery_operand(sub_query_id id) const {
			assert(subquery_operands_.contains(id));
			return subquery_operands_.find(id)->second;
		}

		[[nodiscard]] std::vector<size_t> const &get_odg_tracked_vars_positions(OperandDependencyGraph<htt_t, allocator_type> &graph) const {
			auto &tracked_vars_positions = odg_tracked_vars_positions_[graph.identifier()];
			if (not tracked_vars_positions.empty())
				return tracked_vars_positions;
			auto const &odg_vars_set = graph.operands_var_ids_set();
			for (auto const &[var, pos] : tracked_vars_pos_) {
				if (odg_vars_set.contains(var))
					tracked_vars_positions.push_back(pos);
			}
			return tracked_vars_positions;
		}

		[[nodiscard]] bool all_tracked_vars_done(OperandDependencyGraph<htt_t, allocator_type> &graph) const {
			auto g_id = graph.identifier();
			if (odg_contains_tracked_vars_.contains(g_id))
				return odg_contains_tracked_vars_[g_id];
			auto &all_tv_done = odg_contains_tracked_vars_[g_id];
			auto const &vars_in_operands = graph.operands_var_ids_set();
			all_tv_done = std::all_of(tracked_vars_.begin(), tracked_vars_.end(),
									  [&](char proj_var) { return not vars_in_operands.contains(proj_var); });
			return all_tv_done;
		}

		[[nodiscard]] Operation &get_odg_operator_type(OperandDependencyGraph<htt_t, allocator_type> &graph) const {
			return odg_operator_type_[graph.identifier()];
		}

		[[nodiscard]] std::vector<size_t> const &get_odg_projected_vars_positions(OperandDependencyGraph<htt_t, allocator_type> &graph) const {
			auto &projected_vars_positions = odg_tracked_vars_positions_[graph.identifier()];
			if (not projected_vars_positions.empty())
				return projected_vars_positions;
			auto const &odg_vars_set = graph.operands_var_ids_set();
			for (auto const &[var, pos] : tracked_vars_pos_) {
				if (odg_vars_set.contains(var))
					projected_vars_positions.push_back(pos);
			}
			return projected_vars_positions;
		}

		/**
		 * @return the hypertrie context that should be used for this query
		 * @warning the context is not synchronized in any way and thus cannot be used in parallel
		 * @todo when subquery processing is parallelized care must be taken to give subqueries their own context, or lock this one
		 */
		[[nodiscard]] std::shared_ptr<hypertrie::HypertrieContext<htt_t, allocator_type>> const &tensor_context() const noexcept {
			return tensor_context_;
		}
	};

}// namespace dice::query

#endif//QUERY_QUERY_HPP
